In [1]:
import pandas as pd

data = pd.read_csv("dl_data.csv")

data["Gender"] = data["Gender"].apply(lambda x: int(x == "Male"))
data["Age Group"] = data["Age Group"].apply(lambda x: 0 if x == "Teenager" else 1 if x == "Young Adult" else 2)
data["Race"] = data["Race"].apply(lambda x: 0 if x == "White" else 1 if x == "Black" else 2)
data["Training"] = data["Training"].apply(lambda x: 1 if x == "Basic" else 2 if x == "Advanced" else 0)
data["Reactions"] = data["Reactions"].apply(lambda x: 1 if x == "Average" else 2 if x == "Fast" else 0)
data["Qualified"] = data["Qualified"].apply(lambda x: int(x == "Yes"))

features = data.columns.tolist()
features.remove("Applicant ID")
features.remove("Qualified")

print(features)

X = data[features]
y = data.Qualified

from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, random_state=0)

data.head()

['Gender', 'Age Group', 'Race', 'Training', 'Signals', 'Yield', 'Speed Control', 'Night Drive', 'Road Signs', 'Steer Control', 'Mirror Usage', 'Confidence', 'Parking', 'Theory Test', 'Reactions']

,Applicant ID,Gender,Age Group,Race,Training,Signals,Yield,Speed Control,Night Drive,Road Signs,Steer Control,Mirror Usage,Confidence,Parking,Theory Test,Reactions,Qualified
0,AID0001,1,1,2,0,38.48,30.29,37.03,33.53,39.61,58.16,53.42,35.32,38.19,70.68,1,0
1,AID0002,0,1,1,0,51.76,19.13,63.05,34.87,19.56,16.48,27.97,22.91,24.23,78.18,1,0
2,AID0003,1,2,1,0,30.21,48.13,43.13,42.43,60.93,20.74,28.86,32.32,44.11,79.60,2,1
3,AID0004,1,1,2,0,34.75,47.28,50.49,42.10,22.52,33.87,48.52,24.90,37.56,57.34,1,0
4,AID0005,1,0,2,2,78.52,83.93,59.79,52.68,67.47,89.24,30.31,43.85,55.91,78.44,1,1

In [2]:
data.describe()

,Gender,Age Group,Race,Training,Signals,Yield,Speed Control,Night Drive,Road Signs,Steer Control,Mirror Usage,Confidence,Parking,Theory Test,Reactions,Qualified
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,0.488000,1.070000,1.012000,1.004000,48.525460,47.784000,47.931740,47.877760,47.793440,47.429480,48.157580,47.654440,48.452360,70.623380,1.104000,0.498000
std,0.500357,0.717027,0.820489,0.777942,16.294927,16.062178,15.601242,15.302693,16.042885,15.580004,15.459866,16.056021,15.705702,17.864177,0.708653,0.500497
min,0.000000,0.000000,0.000000,0.000000,0.770000,0.000000,0.000000,1.740000,0.000000,0.000000,0.000000,5.120000,0.000000,40.100000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,0.000000,38.097500,36.915000,37.297500,37.387500,36.547500,37.340000,38.355000,37.020000,37.460000,54.920000,1.000000,0.000000
50%,0.000000,1.000000,1.000000,1.000000,48.415000,48.950000,49.405000,48.160000,49.310000,48.220000,48.360000,48.255000,49.400000,69.855000,1.000000,0.000000
75%,1.000000,2.000000,2.000000,2.000000,59.357500,58.977500,58.392500,58.792500,58.772500,57.515000,58.795000,59.027500,59.262500,86.685000,2.000000,1.000000
max,1.000000,2.000000,2.000000,2.000000,95.610000,94.410000,89.430000,89.930000,88.870000,89.240000,90.770000,90.280000,88.360000,99.750000,2.000000,1.000000

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

forest_model = RandomForestClassifier(random_state=1)
forest_model.fit(train_X, train_y)

predictions = forest_model.predict(test_X)
print(classification_report(test_y, predictions))

              precision    recall  f1-score   support

           0       0.86      0.89      0.87        61
           1       0.89      0.86      0.87        64

    accuracy                           0.87       125
   macro avg       0.87      0.87      0.87       125
weighted avg       0.87      0.87      0.87       125

In [4]:
from pickle import dump

with open("forest_model.pickle", "wb") as f:
    dump(forest_model, f, protocol=5)